/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BlindHireEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptFreelancer"
      | "cancelProject"
      | "createProject"
      | "openDispute"
      | "owner"
      | "projectCount"
      | "projectMilestones"
      | "projectReviewCIDs"
      | "projects"
      | "registerProfileCID"
      | "releaseMilestonePayment"
      | "renounceOwnership"
      | "resolveDispute"
      | "submitReview"
      | "transferOwnership"
      | "uploadDeliverableCID"
      | "userReputations"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeliverableSubmitted"
      | "DisputeOpened"
      | "DisputeResolved"
      | "FreelancerAccepted"
      | "MilestonePaid"
      | "OwnershipTransferred"
      | "ProfileCIDRegistered"
      | "ProjectCancelled"
      | "ProjectCompleted"
      | "ProjectCreated"
      | "ReviewSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptFreelancer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProject",
    values: [string, BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "projectCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projectMilestones",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectReviewCIDs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProfileCID",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseMilestonePayment",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitReview",
    values: [BigNumberish, AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadDeliverableCID",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "userReputations",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptFreelancer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectMilestones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectReviewCIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProfileCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestonePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploadDeliverableCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userReputations",
    data: BytesLike
  ): Result;
}

export namespace DeliverableSubmittedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    milestoneIndex: BigNumberish,
    deliverableCID: string
  ];
  export type OutputTuple = [
    projectId: bigint,
    milestoneIndex: bigint,
    deliverableCID: string
  ];
  export interface OutputObject {
    projectId: bigint;
    milestoneIndex: bigint;
    deliverableCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeOpenedEvent {
  export type InputTuple = [projectId: BigNumberish, initiator: AddressLike];
  export type OutputTuple = [projectId: bigint, initiator: string];
  export interface OutputObject {
    projectId: bigint;
    initiator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    releasedToFreelancerWei: BigNumberish,
    refundedToClientWei: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    releasedToFreelancerWei: bigint,
    refundedToClientWei: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    releasedToFreelancerWei: bigint;
    refundedToClientWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FreelancerAcceptedEvent {
  export type InputTuple = [projectId: BigNumberish, freelancer: AddressLike];
  export type OutputTuple = [projectId: bigint, freelancer: string];
  export interface OutputObject {
    projectId: bigint;
    freelancer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestonePaidEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    milestoneIndex: BigNumberish,
    freelancer: AddressLike,
    amountWei: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    milestoneIndex: bigint,
    freelancer: string,
    amountWei: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    milestoneIndex: bigint;
    freelancer: string;
    amountWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileCIDRegisteredEvent {
  export type InputTuple = [user: AddressLike, profileCID: string];
  export type OutputTuple = [user: string, profileCID: string];
  export interface OutputObject {
    user: string;
    profileCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCancelledEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    client: AddressLike,
    refundAmountWei: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    client: string,
    refundAmountWei: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    client: string;
    refundAmountWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCompletedEvent {
  export type InputTuple = [projectId: BigNumberish];
  export type OutputTuple = [projectId: bigint];
  export interface OutputObject {
    projectId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCreatedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    client: AddressLike,
    projectCID: string,
    totalBudgetWei: BigNumberish,
    deadlineTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    client: string,
    projectCID: string,
    totalBudgetWei: bigint,
    deadlineTimestamp: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    client: string;
    projectCID: string;
    totalBudgetWei: bigint;
    deadlineTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewSubmittedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    reviewer: AddressLike,
    targetUser: AddressLike,
    reviewCID: string,
    rating: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    reviewer: string,
    targetUser: string,
    reviewCID: string,
    rating: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    reviewer: string;
    targetUser: string;
    reviewCID: string;
    rating: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlindHireEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): BlindHireEscrow;
  waitForDeployment(): Promise<this>;

  interface: BlindHireEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptFreelancer: TypedContractMethod<
    [projectId: BigNumberish, freelancer: AddressLike],
    [void],
    "nonpayable"
  >;

  cancelProject: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createProject: TypedContractMethod<
    [
      projectCID: string,
      deadlineDays: BigNumberish,
      milestoneAmountsWei: BigNumberish[]
    ],
    [bigint],
    "payable"
  >;

  openDispute: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  projectCount: TypedContractMethod<[], [bigint], "view">;

  projectMilestones: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, boolean, boolean, string] & {
        amountWei: bigint;
        isCompleted: boolean;
        isPaid: boolean;
        deliverableCID: string;
      }
    ],
    "view"
  >;

  projectReviewCIDs: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  projects: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        client: string;
        freelancer: string;
        projectCID: string;
        totalBudgetWei: bigint;
        deadlineTimestamp: bigint;
        status: bigint;
        createdAt: bigint;
        milestoneCount: bigint;
      }
    ],
    "view"
  >;

  registerProfileCID: TypedContractMethod<
    [profileCID: string],
    [void],
    "nonpayable"
  >;

  releaseMilestonePayment: TypedContractMethod<
    [projectId: BigNumberish, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [
      projectId: BigNumberish,
      releaseToFreelancerWei: BigNumberish,
      refundToClientWei: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitReview: TypedContractMethod<
    [
      projectId: BigNumberish,
      targetUser: AddressLike,
      reviewCID: string,
      ratingScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uploadDeliverableCID: TypedContractMethod<
    [
      projectId: BigNumberish,
      milestoneIndex: BigNumberish,
      deliverableCID: string
    ],
    [void],
    "nonpayable"
  >;

  userReputations: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        completedProjectsCount: bigint;
        totalRatingSum: bigint;
        ratingsCount: bigint;
        disputesWonCount: bigint;
        disputesLostCount: bigint;
        latestProfileCID: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptFreelancer"
  ): TypedContractMethod<
    [projectId: BigNumberish, freelancer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelProject"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createProject"
  ): TypedContractMethod<
    [
      projectCID: string,
      deadlineDays: BigNumberish,
      milestoneAmountsWei: BigNumberish[]
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "projectCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "projectMilestones"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, boolean, boolean, string] & {
        amountWei: bigint;
        isCompleted: boolean;
        isPaid: boolean;
        deliverableCID: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "projectReviewCIDs"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "projects"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        client: string;
        freelancer: string;
        projectCID: string;
        totalBudgetWei: bigint;
        deadlineTimestamp: bigint;
        status: bigint;
        createdAt: bigint;
        milestoneCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProfileCID"
  ): TypedContractMethod<[profileCID: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseMilestonePayment"
  ): TypedContractMethod<
    [projectId: BigNumberish, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [
      projectId: BigNumberish,
      releaseToFreelancerWei: BigNumberish,
      refundToClientWei: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitReview"
  ): TypedContractMethod<
    [
      projectId: BigNumberish,
      targetUser: AddressLike,
      reviewCID: string,
      ratingScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uploadDeliverableCID"
  ): TypedContractMethod<
    [
      projectId: BigNumberish,
      milestoneIndex: BigNumberish,
      deliverableCID: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userReputations"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        completedProjectsCount: bigint;
        totalRatingSum: bigint;
        ratingsCount: bigint;
        disputesWonCount: bigint;
        disputesLostCount: bigint;
        latestProfileCID: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DeliverableSubmitted"
  ): TypedContractEvent<
    DeliverableSubmittedEvent.InputTuple,
    DeliverableSubmittedEvent.OutputTuple,
    DeliverableSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeOpened"
  ): TypedContractEvent<
    DisputeOpenedEvent.InputTuple,
    DisputeOpenedEvent.OutputTuple,
    DisputeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "FreelancerAccepted"
  ): TypedContractEvent<
    FreelancerAcceptedEvent.InputTuple,
    FreelancerAcceptedEvent.OutputTuple,
    FreelancerAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "MilestonePaid"
  ): TypedContractEvent<
    MilestonePaidEvent.InputTuple,
    MilestonePaidEvent.OutputTuple,
    MilestonePaidEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProfileCIDRegistered"
  ): TypedContractEvent<
    ProfileCIDRegisteredEvent.InputTuple,
    ProfileCIDRegisteredEvent.OutputTuple,
    ProfileCIDRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCancelled"
  ): TypedContractEvent<
    ProjectCancelledEvent.InputTuple,
    ProjectCancelledEvent.OutputTuple,
    ProjectCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCompleted"
  ): TypedContractEvent<
    ProjectCompletedEvent.InputTuple,
    ProjectCompletedEvent.OutputTuple,
    ProjectCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCreated"
  ): TypedContractEvent<
    ProjectCreatedEvent.InputTuple,
    ProjectCreatedEvent.OutputTuple,
    ProjectCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewSubmitted"
  ): TypedContractEvent<
    ReviewSubmittedEvent.InputTuple,
    ReviewSubmittedEvent.OutputTuple,
    ReviewSubmittedEvent.OutputObject
  >;

  filters: {
    "DeliverableSubmitted(uint256,uint256,string)": TypedContractEvent<
      DeliverableSubmittedEvent.InputTuple,
      DeliverableSubmittedEvent.OutputTuple,
      DeliverableSubmittedEvent.OutputObject
    >;
    DeliverableSubmitted: TypedContractEvent<
      DeliverableSubmittedEvent.InputTuple,
      DeliverableSubmittedEvent.OutputTuple,
      DeliverableSubmittedEvent.OutputObject
    >;

    "DisputeOpened(uint256,address)": TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;
    DisputeOpened: TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;

    "DisputeResolved(uint256,uint256,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "FreelancerAccepted(uint256,address)": TypedContractEvent<
      FreelancerAcceptedEvent.InputTuple,
      FreelancerAcceptedEvent.OutputTuple,
      FreelancerAcceptedEvent.OutputObject
    >;
    FreelancerAccepted: TypedContractEvent<
      FreelancerAcceptedEvent.InputTuple,
      FreelancerAcceptedEvent.OutputTuple,
      FreelancerAcceptedEvent.OutputObject
    >;

    "MilestonePaid(uint256,uint256,address,uint256)": TypedContractEvent<
      MilestonePaidEvent.InputTuple,
      MilestonePaidEvent.OutputTuple,
      MilestonePaidEvent.OutputObject
    >;
    MilestonePaid: TypedContractEvent<
      MilestonePaidEvent.InputTuple,
      MilestonePaidEvent.OutputTuple,
      MilestonePaidEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProfileCIDRegistered(address,string)": TypedContractEvent<
      ProfileCIDRegisteredEvent.InputTuple,
      ProfileCIDRegisteredEvent.OutputTuple,
      ProfileCIDRegisteredEvent.OutputObject
    >;
    ProfileCIDRegistered: TypedContractEvent<
      ProfileCIDRegisteredEvent.InputTuple,
      ProfileCIDRegisteredEvent.OutputTuple,
      ProfileCIDRegisteredEvent.OutputObject
    >;

    "ProjectCancelled(uint256,address,uint256)": TypedContractEvent<
      ProjectCancelledEvent.InputTuple,
      ProjectCancelledEvent.OutputTuple,
      ProjectCancelledEvent.OutputObject
    >;
    ProjectCancelled: TypedContractEvent<
      ProjectCancelledEvent.InputTuple,
      ProjectCancelledEvent.OutputTuple,
      ProjectCancelledEvent.OutputObject
    >;

    "ProjectCompleted(uint256)": TypedContractEvent<
      ProjectCompletedEvent.InputTuple,
      ProjectCompletedEvent.OutputTuple,
      ProjectCompletedEvent.OutputObject
    >;
    ProjectCompleted: TypedContractEvent<
      ProjectCompletedEvent.InputTuple,
      ProjectCompletedEvent.OutputTuple,
      ProjectCompletedEvent.OutputObject
    >;

    "ProjectCreated(uint256,address,string,uint256,uint256)": TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
    ProjectCreated: TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;

    "ReviewSubmitted(uint256,address,address,string,uint8)": TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;
    ReviewSubmitted: TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;
  };
}
